services:
  cpp_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: latest
    image: cpp:standard
    container_name: cpp_container
    volumes:
      - type: bind
        source: ../
        target: /workspace
        consistency: cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode
